export const HOME_ACTION_TYPES = {
    GET_ALL_CHARACTERS: "GET_ALL_CHARACTERS",
    ADD_FAVORITE: "ADD_FAVORITE",
    REMOVE_FAVORITE: "REMOVE_FAVORITE",
    SEARCH_CHARACTER: "SEARCH_CHARACTER",
    FILTER_CHARACTERS: "FILTER_CHARACTERS",
}

