// interface typesHome {
//     GET_ALL_CHARACTERS: string;
//     ADD_FAVORITE: string;
// }

export const HOME_ACTION_TYPES = {
    GET_ALL_CHARACTERS: "GET_ALL_CHARACTERS",
    ADD_FAVORITE: "ADD_FAVORITE",
    REMOVE_FAVORITE: "REMOVE_FAVORITE",
    SEARCH_CHARACTER: "SEARCH_CHARACTER"
}

